#!/usr/bin/env bash
# Script with for loop to display the text "Best School" 10 times

for (( i=0; i<10; i++ ))
do
    if [ $i -ne 8 ]
    then
        echo "Best School"
    else
	    echo "Hi"
    fi
done