#!/usr/bin/env bash
# Bash script using while loop to display "Best School" 10 times
#       on 9th iteration display "Hi"

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((i++))
done