#!/usr/bin/env bash
# Bash script using while loop to display "Best School" 10 times
#       on 4th iteration diplay "bad luck" & 8th iteration "good luck" 

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done