#!/usr/bin/env bash
# Bash script for displaying numbers 1-20 with case statments
#   Cases:
#      if the number is 4: bad luck from China
#      if the number is 9: bad luck from Japan
#      if the number is 17: bad luck from Italy

count=1

while [ $count -le 20 ]
do
    echo $count
    case $count in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
        esac
    ((count++))
done